=== snail613/yss/server/source/YssQDII/cfg/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/product" xmlns:tns="http://www.example.org/product" elementFormDefault="qualified">
 <element name="oneP">
        	<complexType>
        		<sequence>
        		<element name ="ProductCode" type = "string"/> <!-- 产品代码 -->
				<element name ="ProductName" type = "string"/> <!-- 产品名称 -->
				<element name="Version" type = "string"/> <!-- 版本 -->
				<element name="ProSys" type = "string"/> <!-- 适用系统 -->
				<element name="ProCustomer" type = "string"/> <!-- 适用客户 -->
				<element name="ProductDes" type = "string"/> <!-- 产品说明 -->
        		</sequence>	
        	</complexType>
        </element>
        <element name="multiP">
        	<complexType>
        		<sequence>
        			<element ref ="tns:oneP" maxOccurs = "unbounded"/>
        		</sequence>
        	</complexType>
        </element>
</schema>

=== snail613/yss/server/source/YssQDII/cfg/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:multiP xmlns:tns="http://www.example.org/product" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/product products.xsd ">
  <tns:oneP>
    <tns:ProductCode>4.0</tns:ProductCode>
    <tns:ProductName>估值系统V4.0</tns:ProductName>
    <tns:Version>V1.0</tns:Version>
    <tns:ProSys>QDII4.0</tns:ProSys>
    <tns:ProCustomer>通用</tns:ProCustomer>
    <tns:ProductDes>QDII的预警设置</tns:ProductDes>
  </tns:oneP>
</tns:multiP>
