=== snail613/yss/server/source/YssQDII/cfg/warn-plugin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ysstech.com/warn-plugin" xmlns:pln="http://www.ysstech.com/warn-plugin" elementFormDefault="qualified">
	  <element name = "plug-name" type = "string"></element>
	  
	  <element name = "plug-type">
	 		<complexType>
        		<attribute name ="id"  type ="string"/>
        		<attribute name ="name"  type ="string"/>
        	</complexType>
	  </element>
	  
	  <element name = "plug-range" >
	  		<complexType>
        		<attribute name ="id"  type ="string"/>
        		<attribute name ="name"  type ="string"/>
        	</complexType>
	  </element>
	  
	  <element name = "plug-desc" type = "string"></element>
	  
	  <element name="item">
        	<complexType>
        		<simpleContent>
        			<extension base="string">
        				<attribute name = "id" type = "string"/>
        			</extension>
        		</simpleContent>
        			
        	</complexType>
        </element>
	  
	  <element name = "plug-threshold-items">
	 		<complexType>
        		<sequence>
        			<element  ref ="pln:item" maxOccurs = "unbounded" />
        		</sequence>
        	</complexType>
	  </element>
	  
	  <element name="condition">
        	<complexType>
        		<simpleContent>
        			<extension base="string">
        				<attribute name = "id" type = "string"/>
        			</extension>
        		</simpleContent>	
        	</complexType>
      </element>
      
      <element name = "plug-conditions">
	 		<complexType>
        		<sequence>
        			<element  ref ="pln:condition" maxOccurs = "unbounded" />
        		</sequence>
        	</complexType>
	  </element>
	  
	  <element name = "plug-threshold-rule" type = "string"></element>
	  
	  <element name = "plug-warning-type" type = "string"></element>
	  
	  <element name = "plug-warning-time" type = "string"></element>
	  
	  <element name = "plug-logic" type = "string"></element>
	  
	  <element name="type">
        	<complexType>
        		<simpleContent>
        			<extension base="string">
        				<attribute name = "id" type = "string"/>
        			</extension>
        		</simpleContent>	
        	</complexType>
      </element>
      
      <element name = "plug-result-types" > 
	 		<complexType>
        		<sequence>
        			<element  ref ="pln:type" maxOccurs = "unbounded" />
        		</sequence>
        	</complexType>
	  </element>
	  
	  <element name = "plug-result-show" type = "string"></element>
	  
	  <element name = "plug-url-mapping" type = "string"></element>
	  
	  <element name = "plug-property" type = "string"></element>
	  
	  <element name = "plug-include-product" type = "string"></element>
	  
	  <element name="plug">
        	<complexType>
        		<sequence>
        			<element ref ="pln:plug-name"/>
        			<element ref ="pln:plug-type"/>
        			<element ref ="pln:plug-range"/>
        			<element ref ="pln:plug-desc"/>
        			<element ref ="pln:plug-threshold-items"/>
        			<element ref ="pln:plug-conditions"/>
        			<element ref ="pln:plug-threshold-rule"/>
        			<element ref ="pln:plug-warning-type"/>
        			<element ref ="pln:plug-warning-time"/>
        			<element ref ="pln:plug-logic"/>
        			<element ref ="pln:plug-result-types"/>
        			<element ref ="pln:plug-result-show"/>
        			<element ref ="pln:plug-url-mapping"/>
        			<element ref ="pln:plug-property"/>
        			<element ref ="pln:plug-include-product"/>
        		</sequence>
        		<attribute name ="id" type ="string"/>
        	</complexType>
        </element>
        
        <element name="plugs-app">
        	<complexType>
        		<sequence>
        			<element ref ="pln:plug" maxOccurs = "unbounded"/>
        		</sequence>
        	</complexType>
        </element>
</schema>

=== snail613/yss/server/source/YssQDII/cfg/warn_plugin.xml
<?xml version="1.0" encoding="UTF-8"?>
<pln:plugs-app xmlns:pln="http://www.ysstech.com/warn-plugin" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ysstech.com/warn-plugin warn-plugin.xsd ">
   <pln:plug id="001">  <!-- 单个预警插件定义的节点 -->
    <pln:plug-name>现金计息前检查TA交易数据已结算</pln:plug-name>
    <pln:plug-type id="check" name = "业务检查"/><!-- 插件类型 -->	
    <pln:plug-range id="port" name = "组合"/><!-- 插件适用对象 -->	
    <pln:plug-desc>现金计息前检查TA交易数据已结算</pln:plug-desc><!-- 插件说明 -->	
    <pln:plug-threshold-items><!-- 阀值项目集合 -->
      <pln:item id=" "> </pln:item>
    </pln:plug-threshold-items>
    <pln:plug-conditions><!-- 条件符号 -->
      <pln:condition id=" "> </pln:condition>
    </pln:plug-conditions>
    <pln:plug-threshold-rule>none</pln:plug-threshold-rule><!-- 阀值规则 -->
    <pln:plug-warning-type>继续</pln:plug-warning-type><!-- 提醒类型 -->
    <pln:plug-warning-time> </pln:plug-warning-time><!-- 执行时间--> 
    <pln:plug-logic>and</pln:plug-logic>
    <pln:plug-result-types><!-- 结果类型 -->
      <pln:type id="normal">正常</pln:type>
      <pln:type id="warn">警告</pln:type>
    </pln:plug-result-types>
    <pln:plug-result-show>list</pln:plug-result-show>
    <pln:plug-url-mapping>taSettle</pln:plug-url-mapping>
    <pln:plug-property>估值处理</pln:plug-property>
    <pln:plug-include-product>4.0</pln:plug-include-product>
  </pln:plug>
  
<!-- shashijie 2012-12-25 STORY 3254 增加预警指标 -->
<pln:plug id="totleMoney">  <!-- 单个预警插件定义的节点 -->
  <pln:plug-name>检查交易数据结算金额=成交金额+利息+-费用</pln:plug-name>
  <pln:plug-type id="check" name = "业务检查"/><!-- 插件类型 -->	
  <pln:plug-range id="port" name = "组合"/><!-- 插件适用对象 -->	
  <pln:plug-desc>证券(场内)买卖交易数据的成交金额+-费用后，要等于该笔交易的实际结算金额</pln:plug-desc><!-- 插件说明 -->	
  <pln:plug-threshold-items><!-- 阀值项目集合 -->
    <pln:item id=" "> </pln:item>
  </pln:plug-threshold-items>
  <pln:plug-conditions><!-- 条件符号 -->
    <pln:condition id=" "> </pln:condition>
  </pln:plug-conditions>
  <pln:plug-threshold-rule>none</pln:plug-threshold-rule><!-- 阀值规则 -->
  <pln:plug-warning-type>继续</pln:plug-warning-type><!-- 提醒类型 -->
  <pln:plug-warning-time> </pln:plug-warning-time><!-- 执行时间--> 
  <pln:plug-logic>and</pln:plug-logic>
  <pln:plug-result-types><!-- 结果类型 -->
    <pln:type id="normal">正常</pln:type>
    <pln:type id="warn">警告</pln:type>
  </pln:plug-result-types>
  <pln:plug-result-show>list</pln:plug-result-show>
  <pln:plug-url-mapping>totleMoney</pln:plug-url-mapping>
  <pln:plug-property>估值处理</pln:plug-property>
  <pln:plug-include-product>4.0</pln:plug-include-product>
</pln:plug>
<!-- end shashijie 2012-12-25 STORY 3254-->
<!-- zhaoxianlin 2013-03-08 STORY #3484 证券停牌提示  增加预警指标 -->
<pln:plug id="checkDelist">  <!-- 单个预警插件定义的节点 -->
  <pln:plug-name>检查证券行情与上一日对比是否相同</pln:plug-name>
  <pln:plug-type id="check" name = "业务检查"/><!-- 插件类型 -->	
  <pln:plug-range id="port" name = "组合"/><!-- 插件适用对象 -->	
  <pln:plug-desc>检查证券行情与上一日对比是否相同</pln:plug-desc><!-- 插件说明 -->	
  <pln:plug-threshold-items><!-- 阀值项目集合 -->
    <pln:item id=" "> </pln:item>
  </pln:plug-threshold-items>
  <pln:plug-conditions><!-- 条件符号 -->
    <pln:condition id=" "> </pln:condition>
  </pln:plug-conditions>
  <pln:plug-threshold-rule>none</pln:plug-threshold-rule><!-- 阀值规则 -->
  <pln:plug-warning-type>继续</pln:plug-warning-type><!-- 提醒类型 -->
  <pln:plug-warning-time> </pln:plug-warning-time><!-- 执行时间--> 
  <pln:plug-logic>and</pln:plug-logic>
  <pln:plug-result-types><!-- 结果类型 -->
    <pln:type id="normal">正常</pln:type>
    <pln:type id="warn">警告</pln:type>
  </pln:plug-result-types>
  <pln:plug-result-show>list</pln:plug-result-show>
  <pln:plug-url-mapping>checkDelist</pln:plug-url-mapping>
  <pln:plug-property>估值处理</pln:plug-property>
  <pln:plug-include-product>4.0</pln:plug-include-product>
</pln:plug>
<!-- end zhaoxianlin 2013-03-08 STORY #3484 证券停牌提示  增加预警指标-->
  
  <!--add by songjie 2014.05.10 STORY #15961 需求上海-[交银施罗德]QDIIV4.0[紧急]20140401001 start-->
  <pln:plug id="CheckCashStockScaleOfNav">  <!-- 单个预警插件定义的节点 -->
    <pln:plug-name>本币现金占总净值比例</pln:plug-name>
    <pln:plug-type id="check" name = "业务提醒"/><!-- 插件类型 -->	
    <pln:plug-range id="port" name = "组合"/><!-- 插件适用对象 -->	
    <pln:plug-desc>所有现金库存的本位币合计值除以该日资产净值，当它的百分比小于等于阀值中所设置金额，需要给出提示</pln:plug-desc><!-- 插件说明 -->	
    <pln:plug-threshold-items><!-- 阀值项目集合 -->
      <pln:item id="scale">百分比</pln:item>
    </pln:plug-threshold-items>
    <pln:plug-conditions><!-- 条件符号 -->
      <pln:condition id="scale">%</pln:condition>
    </pln:plug-conditions>
    <pln:plug-threshold-rule> </pln:plug-threshold-rule><!-- 阀值规则 -->
    <pln:plug-warning-type>继续</pln:plug-warning-type><!-- 提醒类型 -->
    <pln:plug-warning-time> </pln:plug-warning-time><!-- 执行时间--> 
    <pln:plug-logic>and</pln:plug-logic>
    <pln:plug-result-types><!-- 结果类型 -->
      <pln:type id="normal">正常</pln:type>
      <pln:type id="warn">提醒</pln:type>
    </pln:plug-result-types>
    <pln:plug-result-show>list</pln:plug-result-show>
    <pln:plug-url-mapping>valCheck</pln:plug-url-mapping>
    <pln:plug-property>估值处理</pln:plug-property>
    <pln:plug-include-product>4.0</pln:plug-include-product>
  </pln:plug>
  <!--add by songjie 2014.05.10 STORY #15961 需求上海-[交银施罗德]QDIIV4.0[紧急]20140401001 end-->
  
  <!-- add by songjie 2013.40.28 STORY #3895 需求深圳-(南方基金)QDII估值系统V4.0(紧急)20130425001 start -->
  <pln:plug id="checkYesNavScale">  <!-- 单个预警插件定义的节点 -->
    <pln:plug-name>停牌证券当日市值 / 前一估值日的资产净值  >= 0.25%</pln:plug-name>
    <pln:plug-type id="check" name = "业务检查"/><!-- 插件类型 -->	
    <pln:plug-range id="port" name = "组合"/><!-- 插件适用对象 -->	
    <pln:plug-desc>停牌证券当日市值 / 前一估值日的资产净值 >= 0.25%</pln:plug-desc><!-- 插件说明 -->	
    <pln:plug-threshold-items><!-- 阀值项目集合 -->
      <pln:item id=" "> </pln:item>
    </pln:plug-threshold-items>
    <pln:plug-conditions><!-- 条件符号 -->
      <pln:condition id=" "> </pln:condition>
    </pln:plug-conditions>
    <pln:plug-threshold-rule>none</pln:plug-threshold-rule><!-- 阀值规则 -->
    <pln:plug-warning-type>继续</pln:plug-warning-type><!-- 提醒类型 -->
    <pln:plug-warning-time> </pln:plug-warning-time><!-- 执行时间--> 
    <pln:plug-logic>and</pln:plug-logic>
    <pln:plug-result-types><!-- 结果类型 -->
      <pln:type id="normal">正常</pln:type>
      <pln:type id="warn">警告</pln:type>
    </pln:plug-result-types>
    <pln:plug-result-show>list</pln:plug-result-show>
    <pln:plug-url-mapping>valCheck</pln:plug-url-mapping>
    <pln:plug-property>估值处理</pln:plug-property>
    <pln:plug-include-product>4.0</pln:plug-include-product>
  </pln:plug>
  <!-- add by songjie 2013.40.28 STORY #3895 需求深圳-(南方基金)QDII估值系统V4.0(紧急)20130425001 end -->
  
  <pln:plug id="002">  <!-- 单个预警插件定义的节点 -->
    <pln:plug-name>交易日无 TA数据提醒</pln:plug-name>
    <pln:plug-type id="check" name = "业务检查"/><!-- 插件类型 -->	
    <pln:plug-range id="port" name = "组合"/><!-- 插件适用对象 -->	
    <pln:plug-desc>交易日TA数据未读取给出提示</pln:plug-desc><!-- 插件说明 -->	
    <pln:plug-threshold-items><!-- 阀值项目集合 -->
      <pln:item id=" "> </pln:item>
    </pln:plug-threshold-items>
    <pln:plug-conditions><!-- 条件符号 -->
      <pln:condition id=" "> </pln:condition>
    </pln:plug-conditions>
    <pln:plug-threshold-rule>none</pln:plug-threshold-rule><!-- 阀值规则 -->
    <pln:plug-warning-type>继续</pln:plug-warning-type><!-- 提醒类型 -->   
    <pln:plug-warning-time> </pln:plug-warning-time><!-- 执行时间-->  
    <pln:plug-logic>and</pln:plug-logic>
    <pln:plug-result-types><!-- 结果类型 -->
      <pln:type id="normal">正常</pln:type>
      <pln:type id="warn">警告</pln:type>
    </pln:plug-result-types>
    <pln:plug-result-show>list</pln:plug-result-show>
    <pln:plug-url-mapping>taTrade</pln:plug-url-mapping>
    <pln:plug-property>TA业务</pln:plug-property>
    <pln:plug-include-product>4.0</pln:plug-include-product>
  </pln:plug>

   <pln:plug id="CheckSecurityIsNull">  <!-- 单个预警插件定义的节点 -->
    <pln:plug-name>证券是否卖空</pln:plug-name>
    <pln:plug-type id="check" name = "业务检查"/><!-- 插件类型 -->	
    <pln:plug-range id="port" name = "组合"/><!-- 插件适用对象 -->	
    <pln:plug-desc>发生证券卖空时提示</pln:plug-desc><!-- 插件说明 -->	
    <pln:plug-threshold-items><!-- 阀值项目集合 -->
      <pln:item id=" "> </pln:item>
    </pln:plug-threshold-items>
    <pln:plug-conditions><!-- 条件符号 -->
      <pln:condition id=" "> </pln:condition>
    </pln:plug-conditions>
    <pln:plug-threshold-rule>none</pln:plug-threshold-rule><!-- 阀值规则 -->
    <pln:plug-warning-type>继续</pln:plug-warning-type><!-- 提醒类型 -->
    <pln:plug-warning-time>日终估值前</pln:plug-warning-time><!-- 执行时间--> 
    <pln:plug-logic>and</pln:plug-logic>
    <pln:plug-result-types><!-- 结果类型 -->
      <pln:type id="normal">正常</pln:type>
      <pln:type id="warn">提醒</pln:type>
    </pln:plug-result-types>
    <pln:plug-result-show>list</pln:plug-result-show>
    <pln:plug-url-mapping>valCheck</pln:plug-url-mapping>
    <pln:plug-property>交易证券</pln:plug-property>
    <pln:plug-include-product>4.0</pln:plug-include-product>
  </pln:plug>
  
  <pln:plug id="CheckDelayTrade">  <!-- 单个预警插件定义的节点 -->
    <pln:plug-name>今日延迟结算的交易记录</pln:plug-name>
    <pln:plug-type id="check" name = "业务检查"/><!-- 插件类型 -->	
    <pln:plug-range id="port" name = "组合"/><!-- 插件适用对象 -->	
    <pln:plug-desc>检查日有延迟结算记录时提示</pln:plug-desc><!-- 插件说明 -->	
    <pln:plug-threshold-items><!-- 阀值项目集合 -->
      <pln:item id=" "> </pln:item>
    </pln:plug-threshold-items>
    <pln:plug-conditions><!-- 条件符号 -->
      <pln:condition id=" "> </pln:condition>
    </pln:plug-conditions>
    <pln:plug-threshold-rule>none</pln:plug-threshold-rule><!-- 阀值规则 -->
    <pln:plug-warning-type>继续</pln:plug-warning-type><!-- 提醒类型 -->
    <pln:plug-warning-time>日终估值前</pln:plug-warning-time><!-- 执行时间--> 
    <pln:plug-logic>and</pln:plug-logic>
    <pln:plug-result-types><!-- 结果类型 -->
      <pln:type id="normal">正常</pln:type>
      <pln:type id="warn">提醒</pln:type>
    </pln:plug-result-types>
    <pln:plug-result-show>list</pln:plug-result-show>
    <pln:plug-url-mapping>valCheck</pln:plug-url-mapping>
    <pln:plug-property>交易证券</pln:plug-property>
    <pln:plug-include-product>4.0</pln:plug-include-product>
